In [47]:
import numpy as np
import scipy.optimize as opt

m = 5
n = 3

A = np.random.uniform(-1, 1, size=(m, n))
b = np.random.uniform(-10, 10, size=(m,))
c = np.random.uniform(0, 1, size=(n,))
C = np.diag(c)

def callback(res: opt.OptimizeResult):
    print(f"Iteration {res.nit}:", res.fun, res.x, res.slack, res.con, sep="\n\t")
    

print(opt.linprog(c, A_ub=A, b_ub=b, method="interior-point", callback=callback))

Iteration 0:
	2.1526944234074676
	[1. 1. 1.]
	[-10.31434358   6.8761623    6.54034529  -1.97613056  -4.12413388]
	[]
Iteration 1:
	7.7343510358454335
	[0.84006904 3.71147633 5.52088424]
	[-8.5092983  10.0370864   9.0942369  -3.05289216 -1.68531302]
	[]
Iteration 2:
	16.456655698881285
	[ 1.9352031  10.72419893  9.86125672]
	[-11.26582408  11.37581802  15.29483706  -5.66520009   2.62757857]
	[]
Iteration 3:
	18.5973512783187
	[ 2.45061432  8.22182032 13.4035896 ]
	[-5.81098282 14.06665092 12.60216938 -6.5807796   2.59622073]
	[]
Iteration 4:
	18.205536753725767
	[ 2.45998136  8.06892651 13.06403962]
	[-5.99238437 13.8233772  12.46013602 -6.50300205  2.43463887]
	[]
Iteration 5:
	18.205536752671563
	[ 2.45998136  8.06892651 13.06403961]
	[-5.99238437 13.8233772  12.46013602 -6.50300205  2.43463887]
	[]
 message: The algorithm terminated successfully and determined that the problem is infeasible.
 success: False
  status: 2
     fun: 18.205536752671563
       x: [ 2.460e+00  8.069e+00  1.

/tmp/ipykernel_453441/2419071826.py:16: DeprecationWarning: `method='interior-point'` is deprecated and will be removed in SciPy 1.11.0. Please use one of the HiGHS solvers (e.g. `method='highs'`) in new code.
  print(opt.linprog(c, A_ub=A, b_ub=b, method="interior-point", callback=callback))
